apiVersion: tmax.io/v1
kind: ClusterTemplate
metadata:
  name: devpi-package-server
  annotations:
    template-version: 5.0.5
    tested-operator-version: 0.2.5
imageUrl: https://devpi.net/docs/devpi/devpi/stable/+doc/_static/logo.svg
provider: tmax
recommend: false
shortDescription: Devpi package server for python pip
longDescription: Devpi package server for python pip
urlDescription: https://github.com/devpi/devpi
categories:
- devpi
- package-server
- python
- pip
parameters:
- name: DEPLOY_NAME
  displayName: DeploymentName
  description: Deployment name
  required: true
  valueType: string
- name: STORAGE
  displayName: StorageSize
  description: Size of a storage (e.g., 100Mi, 10Gi, ...)
  required: true
  valueType: string
- name: STORAGE_CLASS
  displayName: StorageClass
  description: Storage class
  value: csi-cephfs-sc
  required: true
  valueType: string
plans:
- bindable: false
  description: Devpi package server
  name: devpi-plan0
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${DEPLOY_NAME}-svc
    labels:
      app: ${DEPLOY_NAME}
  spec:
    selector:
      app: ${DEPLOY_NAME}
    ports:
    - name: http
      port: 3141
      protocol: TCP
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${DEPLOY_NAME}-pvc
    labels:
      app: ${DEPLOY_NAME}
  spec:
    storageClassName: ${STORAGE_CLASS}
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${STORAGE}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${DEPLOY_NAME}
    labels:
      app: ${DEPLOY_NAME}
  spec:
    selector:
      matchLabels:
        app: ${DEPLOY_NAME}
    template:
      metadata:
        labels:
          app: ${DEPLOY_NAME}
      spec:
        containers:
        - name: devpi
          image: docker.io/tmaxcloudck/devpi:5.5.0
          imagePullPolicy: Always
          ports:
          - containerPort: 3141
          volumeMounts:
          - name: devpi-data
            mountPath: /devpi
        volumes:
        - name: devpi-data
          persistentVolumeClaim:
            claimName: ${DEPLOY_NAME}-pvc
