apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: verdaccio-package-server-instance
  namespace: default
  annotations:
    template-version: 5.0.3
    tested-operator-version: 1.1.0
spec:
  clustertemplate:
    metadata:
      name: verdaccio-package-server
    parameters:
    - name: DEPLOY_NAME
      value: verdaccio-private-1
    - name: STORAGE
      value: 10Gi
    - name: STORAGE_CLASS
      value: csi-cephfs-sc

