apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: vanilla-vscode-template-instance
  namespace: default
  annotations:
    template-version: 5.0.4
    tested-operator-version: 0.2.1
spec:
  clustertemplate:
    metadata:
      name: vanilla-vscode-template
    parameters:
    - name: APP_NAME
      value: vanilla-vscode-deploy
    - name: STORAGE
      value: 30Gi
    - name: STORAGE_CLASS
      value: csi-cephfs-sc
    - name: SERVICE_TYPE
      value: Ingress
