apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: mysql-template-instance
  namespace: default
  annotations:
    template-version: 5.0.4
    tested-operator-version: 0.2.1
spec:
  clustertemplate:
    metadata:
      name: mysql-template
    parameters:
    - name: APP_NAME
      value: mysql-sample-app
    - name: DB_STORAGE
      value: "10Gi"
    - name: STORAGE_CLASS
      value: csi-cephfs-sc
    - name: SERVICE_TYPE
      value: ClusterIP
    - name: MYSQL_USER
      value: root1
    - name: MYSQL_PASSWORD
      value: tmax@23
    - name: MYSQL_DATABASE
      value: root1
