apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: redis-template-instance
  namespace: default
  annotations:
    template-version: 5.0.3
    tested-operator-version: 1.1.0
spec:
  clustertemplate:
    metadata:
      name: redis-template
    parameters:
    - name: APP_NAME
      value: redis-sample-app
    - name: DB_STORAGE
      value: "10Gi"
    - name: STORAGE_CLASS
      value: csi-cephfs-sc
    - name: SERVICE_TYPE
      value: ClusterIP
    - name: DATABASE_SERVICE_NAME
      value: redis
    - name: REDIS_PASSWORD
      value: tmax@23
