apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: gitlab-public-s2b-templateinstance
  namespace: shlee
spec:
  clustertemplate:
    metadata:
      name: java-s2b-template
    parameters:
    - name: POD_NAME
      value: "gitlab-public-s2b-pod" 
    - name: GIT_REPO
      value: "https://gitlab.com/sihyunglee823/gitlab-test-public.git"
    - name: USR_SECRET_NAME
      value: ""
    - name: GITHUB_ID
      value: ""
    - name: GITLAB_TOKEN_NAME
      value: ""
    - name: USR_BUILD_CMD
      value: "mvn clean; mvn compile; mvn package; mvn install;"
    - name: USR_RUN_CMD
      value: "java -cp target/jb-hello-world-maven-0.1.0.jar hello.HelloWorld;"
    - name: JDK_VERSION
      value: "11"
    - name: MVN_VERSION
      value: "3.8.3"
    - name: GRADLE_VERSION
      value: ""
