apiVersion: tmax.io/v1
kind: ClusterTemplate
metadata:
  name: java-s2b-template
categories:
- source2build
- java
- maven
- gradle
imageUrl: ""
urlDescription: ""
longDescription: ""
markdownDescription: ""
objectKinds:
- Deployment
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${POD_NAME}-java-s2b
    labels:
      app: ${POD_NAME}-java-s2b
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ${POD_NAME}-java-s2b
    template:
      metadata:
        labels:
          app: ${POD_NAME}-java-s2b
      spec:
        serviceAccountName: ${POD_NAME}-s2b-account
        initContainers:
        - command:
          - /bin/bash
          - -c
          - -x
          - |
            SECRET="${USR_SECRET_NAME}"
            if [[ "$SECRET" != "" ]]; then
              kubectl get secret ${USR_SECRET_NAME} -n $(USR_NAMESPACE) -o jsonpath='{.data}' > /secret/usr_secret
            fi
          image: docker.io/bitnami/kubectl:1.20.10
          imagePullPolicy: IfNotPresent
          name: create-secret-for-private
          volumeMounts:
          - name: git-token
            mountPath: /secret
          env:
          - name: USR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        - name: s2b-build-container
          image: tmaxcloudck/source2build:v5.1 
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: git-token
            mountPath: /secret
          env:
          - name: GIT_REPO
            value: ${GIT_REPO}
          - name: GITHUB_ID
            value: ${GITHUB_ID}
          - name: GITLAB_TOKEN_NAME
            value: ${GITLAB_TOKEN_NAME}
          - name: USR_BUILD_CMD
            value: ${USR_BUILD_CMD}
          - name: JDK_VERSION
            value: ${JDK_VERSION}
          - name: MVN_VERSION
            value: ${MVN_VERSION}
          - name: GRADLE_VERSION
            value: ${GRADLE_VERSION}
        containers:
        - name: s2b-run-container
          image: tmaxcloudck/source2build:jre
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: git-token
            mountPath: /secret
          env:
          - name: USR_RUN_CMD
            value: ${USR_RUN_CMD}
          - name: JDK_VERSION
            value: ${JDK_VERSION}
          - name: GRADLE_VERSION
            value: ${GRADLE_VERSION}          
          ports:
          - containerPort: 9090
          - containerPort: 80
          - containerPort: 8080
        volumes:
        - name: git-token
          emptyDir: {}
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ${POD_NAME}-s2b-account
    namespace: $(USR_NAMESPACE)
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: secret-reader-s2b
    namespace: $(USR_NAMESPACE)
  rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: read-secrets-s2b
    namespace: $(USR_NAMESPACE)
  subjects:
  - kind: ServiceAccount
    name: ${POD_NAME}-s2b-account
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: secret-reader-s2b
- apiVersion: v1
  kind: Service
  metadata:
    name: ${POD_NAME}-java-s2b-svc
    labels:
      app: ${POD_NAME}-java-s2b
  spec:
    selector:
      app: ${POD_NAME}-java-s2b
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: apache
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: nginx
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: http
parameters:
- description: pod name
  displayName: POD_NAME
  name: POD_NAME
  required: true
  value: java-s2b-pod
  valueType: string
- description: git repository
  displayName: GIT_REPO
  name: GIT_REPO
  required: true
  valueType: string
- description: secret name containing git token for a private repository
  displayName: USR_SECRET_NAME  
  name: USR_SECRET_NAME
  required: false
  value: ""
  valueType: string
- description: github user id for a github private repository
  displayname: GITHUB_ID
  name: GITHUB_ID
  required: false
  value: ""
  valueType: string
- description: gitlab token name for a gitlab private project
  displayname: GITLAB_TOKEN_NAME
  name: GITLAB_TOKEN_NAME
  required: false
  value: ""
  valueType: string
- description: user build command
  displayName: USR_BUILD_CMD
  name: USR_BUILD_CMD
  required: true
  valueType: string
- description: user run command
  displayName: USR_RUN_CMD
  name: USR_RUN_CMD
  required: true
  valueType: string
- description: jdk version
  diaplayName: JDK_VERSION
  name: JDK_VERSION
  required: false
  value: 12
  valueType: string
- description: maven version
  displayName: MVN_VERSION
  name: MVN_VERSION
  required: false
  value: "3.8.3"
  valueType: string
- description: gradle version
  displayName: GRADLE_VERSION
  name: GRADLE_VERSION
  required: false
  value: "7.2"
  valueType: string
