apiVersion: tmax.io/v1
kind: ClusterTemplate
metadata:
  name: java-s2b-template
categories:
- source2build
- java
- maven
- gradle
imageUrl: ""
urlDescription: ""
longDescription: ""
markdownDescription: ""
objectKinds:
- Deployment
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${POD_NAME}-java-s2b
    labels:
      app: ${POD_NAME}-java-s2b
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ${POD_NAME}-java-s2b
    template:
      metadata:
        labels:
          app: ${POD_NAME}-java-s2b
      spec:
        containers:
        - name: java-s2b-container
          image: tmaxcloudck/source2build:v3.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 9090
          - containerPort: 80
          - containerPort: 8080
          env:
          - name: GIT_REPO
            value: ${GIT_REPO}
          - name: USR_SECRET_NAME
            valueFrom:
              secretKeyRef:
                name: ${USR_SECRET_NAME}
                key: git-token
          - name: GITHUB_ID
            value: ${GITHUB_ID}
          - name: GITLAB_TOKEN_NAME
            value: ${GITLAB_TOKEN_NAME}
          - name: USR_BUILD_CMD
            value: ${USR_BUILD_CMD}
          - name: USR_RUN_CMD
            value: ${USR_RUN_CMD}

- apiVersion: v1
  kind: Service
  metadata:
    name: ${POD_NAME}-java-s2b-svc
    labels:
      app: ${POD_NAME}-java-s2b
  spec:
    selector:
      app: ${POD_NAME}-java-s2b
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: apach
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: nginx
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: http

parameters:
- description: pod name
  displayName: POD_NAME
  name: POD_NAME
  required: true
  value: java-s2b-pod
  valueType: string
- description: git repository
  displayName: GIT_REPO
  name: GIT_REPO
  required: true
  valueType: string
- description: secret name containing git access token
  displayName: USR_SECRET_NAME
  name: USR_SECRET_NAME
  required: true
  value: ""
  valueType: string
- description: github user id for a github private repository
  displayname: GITHUB_ID
  name: GITHUB_ID
  required: false
  value: ""
- description: gitlab token name for a gitlab private project
  displayname: GITLAB_TOKEN_NAME
  name: GITLAB_TOKEN_NAME
  required: false
  value: ""
- description: user build command
  displayName: USR_BUILD_CMD
  name: USR_BUILD_CMD
  required: true
  valueType: string
- description: user run command
  displayName: USR_RUN_CMD
  name: USR_RUN_CMD
  required: true
  valueType: string


