apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: springboot-s2b-templateinstance
  namespace: shlee
spec:
  clustertemplate:
    metadata:
      name: java-s2b-template
    parameters:
    - name: POD_NAME
      value: "springboot-s2b-pod" 
    - name: GIT_REPO
      value: "https://gitlab.com/sihyunglee823/springtest.git"
    - name: USR_SECRET_NAME
      value: ""
    - name: GITHUB_ID
      value: ""
    - name: GITLAB_TOKEN_NAME
      value: ""
    - name: USR_BUILD_CMD
      value: "gradle init; gradle build;"
    - name: USR_RUN_CMD
      value: "gradle bootRun;"
    - name: JDK_VERSION
      value: "11"
    - name: MVN_VERSION
      value: ""
    - name: GRADLE_VERSION
      value: "7.2"
