apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: jenkins-template-instance
  namespace: default
  annotations:
    template-version: 5.0.5
    tested-operator-version: 0.2.5
spec:
  clustertemplate:
    metadata:
      name: jenkins-template
    parameters:
    - name: APP_NAME
      value: jenkins-test-deploy
    - name: STORAGE
      value: 10Gi
    - name: STORAGE_CLASS
      value: csi-cephfs-sc
    - name: SERVICE_TYPE
      value: LoadBalancer
