apiVersion: tmax.io/v1
kind: ClusterTemplate
metadata:
  name: ot-container-kit-redis-exporter-cluster-template
shortDescription: "Redis Exporter Cluster Deployment"
longDescription: "Redis Exporter Cluster with redis-operator"
urlDescription: https://ot-container-kit.github.io/redis-operator/
provider: tmax
categories:
- redis
- exporter
- cluster
- ot-container-kit
parameters:
- name: APP_NAME
  displayName: A Redis Exporter Cluster
  description: metadata name
  value: "redis-exporter-cluster"
  required: true
  valueType: string
- name: REDIS_EXPORTER_CLUSTER_SECRET_PASSWORD
  displayName: Redis Secret password
  description: Redis Secret password
  value: "abcd=="
  required: true
  valueType: string
- name: REDIS_EXPORTER_CLUSTER_REPLICA_COUNT
  displayName: Redis Exporter Cluster Replica Count
  description: Number of redis exporter cluster pair(leader, follower), greater 3 or equal to
  value: 3
  required: true
  valueType: number
- name: REDIS_EXPORTER_CLUSTER_STORAGE
  displayName: Redis Exporter Cluster Storage
  description: Redis Exporter Cluster storage size
  value: 5Gi
  required: true
  valueType: string
- name: STORAGE_CLASS
  displayName: Storage Class
  description: Storage class name
  value: csi-cephfs-sc
  required: true
  valueType: string
- name: REDIS_EXPORTER_CLUSTER_RESOURCE_CPU
  displayName: Redis Exporter Cluster Resource CPU
  description: Redis Exporter Cluster resource request, CPU (e.g., 1)
  value: 1
  required: true
  valueType: string
- name: REDIS_EXPORTER_CLUSTER_RESOURCE_MEM
  displayName: Redis Exporter Cluster Resource Mem
  description: Redis Exporter Cluster Resource request, Mem (e.g., 1Gi)
  value: 1Gi
  required: true
  valueType: string
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${APP_NAME}-secret-cluster-exporter
  stringData:
    password: ${REDIS_EXPORTER_CLUSTER_SECRET_PASSWORD}
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    name: ${APP_NAME}-monitoring-exporter-cluster
    labels:
      app: ${APP_NAME}-leader
      release: prometheus
  spec:
    selector:
      matchLabels:
        app: ${APP_NAME}-leader
    endpoints:
    - port: "redis-exporter"
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APP_NAME}-svc-exporter-cluster
  spec:
    selector:
      app: ${APP_NAME}-leader
    ports:
    - name: redis-exporter-cluster
      protocol: TCP
      port: 6379
      targetPort: 6379
    - name: redis-exporter
      protocol: TCP
      port: 9121
      targetPort: 9121
- apiVersion: redis.redis.opstreelabs.in/v1beta1
  kind: RedisCluster
  metadata:
    name: ${APP_NAME}
  spec:
    clusterSize: ${REDIS_EXPORTER_CLUSTER_REPLICA_COUNT}
    kubernetesConfig:
      image: quay.io/opstree/redis:v6.2.5
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: ${REDIS_EXPORTER_CLUSTER_RESOURCE_CPU}
          memory: ${REDIS_EXPORTER_CLUSTER_RESOURCE_MEM}
        limits:
          cpu: ${REDIS_EXPORTER_CLUSTER_RESOURCE_CPU}
          memory: ${REDIS_EXPORTER_CLUSTER_RESOURCE_MEM}
      redisSecret:
        name: ${APP_NAME}-secret-cluster-exporter
        key: password
    redisExporter:
      enabled: true
      image: quay.io/opstree/redis-exporter:1.0
      imagePullPolicy: Always
      resources:
        requests:
          cpu: ${REDIS_EXPORTER_CLUSTER_RESOURCE_CPU}
          memory: ${REDIS_EXPORTER_CLUSTER_RESOURCE_MEM}
        limits:
          cpu: ${REDIS_EXPORTER_CLUSTER_RESOURCE_CPU}
          memory: ${REDIS_EXPORTER_CLUSTER_RESOURCE_MEM}
      env:
      - name: REDIS_EXPORTER_INCL_SYSTEM_METRICS
        value: "true"
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: ${STORAGE_CLASS}
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: ${REDIS_EXPORTER_CLUSTER_STORAGE}
---
