apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: mysql-ha-template-instance
  namespace: default
  annotations:
    template-version: sh-pilot
    tested-operator-version: v0.3.2
spec:
  clustertemplate:
    metadata:
      name: mysql-ha-template
    parameters:
    - name: APP_NAME
      value: mysql-ha-test-deploy
    - name: REPLICA
      value: 4

