apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: mysql-ha-template-instance
  namespace: default
  annotations:
    template-version: 5.0.4
    tested-operator-version: 0.2.1
spec:
  clustertemplate:
    metadata:
      name: mysql-ha-template
    parameters:
    - name: APP_NAME
      value: mysql-ha-test-deploy
    - name: REPLICA
      value: 4
    - name: STORAGE_CLASS
      value: csi-cephfs-sc

