apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: konga-only-instance
  # 적용하고자 하는 namespace를 생성 후 해당 namespace 적용
  namespace: smlee
spec:
  clustertemplate:
    metadata:
      name: konga-only-template
    parameters:
      #사용하고자 하는 postgres의 user ID
    - name: DB_USER
      value: "userid"

      #사용하고자 하는 PWD
    - name: DB_PASSWORD
      value: "userpwd"

      #사용하고자 하는 DB 명
    - name: DB_DATABASE
      value: "userdb"
    
    - name: DB_HOST
      value: postgres-service

