apiVersion: tmax.io/v1
kind: ClusterTemplate
metadata:
  name: konga-template
shortDescription: "Kong with Konga Demo Template"
urlDescription: "https://https://github.com/pantsel/konga"
provider: tmax
categories:
- konga

parameters:
- name: DB_USER
  displayName: db_user
  description: postgres db user id
  value: kong
  required: true
  valueType: string

- name: DB_PASSWORD
  displayName: db_password
  description: postgres db user password
  value: kong
  required: true
  valueType: string

- name: DB_DATABASE
  displayName: db_database
  description: postgres db table name
  value: kong
  required: true
  valueType: string

objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: konga
    labels:
      app.kubernetes.io/name: konga
      app.kubernetes.io/instance: konga
  spec:
    replicas: 1
    selector:
      matchLabels:
        app.kubernetes.io/name: konga
        app.kubernetes.io/instance: konga
    template:
      metadata:
        labels:
          app.kubernetes.io/name: konga
          app.kubernetes.io/instance: konga
      spec:
        containers:
          - name: konga
            image: tmaxcloudck/konga:0.14.9
            imagePullPolicy: IfNotPresent
            ports:
              - name: http
                containerPort: 1337
                protocol: TCP
            livenessProbe:
              httpGet:
                path: /
                port: http
            readinessProbe:
              httpGet:
                path: /
                port: http
            env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PORT
              value: "1337"
            - name: NODE_ENV
              value: "development"
            - name: KONGA_HOOK_TIMEOUT
              value: "60000"
            - name: DB_ADAPTER
              value: "postgres"
            - name: DB_HOST
              value: "postgres.$(NAMESPACE).svc.cluster.local"
            - name: DB_USER
              value: ${DB_USER}
            - name: DB_PASSWORD
              value: ${DB_PASSWORD}
            - name: DB_DATABASE
              value: ${DB_DATABASE}
            - name: DB_PG_SCHEMA
              value: "public"
            - name: KONGA_LOG_LEVEL
              value: "debug"
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"      
- apiVersion: v1
  kind: Service
  metadata:
    name: konga-loadbalancer
  spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 1337
    selector:
      app.kubernetes.io/instance: konga
