apiVersion: tmax.io/v1
kind: ClusterTemplate
metadata:
  name: redis-template
shortDescription: "Redis Template with exporter"
urlDescription: "https://redis.io"
provider: tmax
categories:
- redis

parameters:
- name: REDIS_NAME
  displayName: redis_name
  description: redis instnace name
  value: my-redis
  required: true
- name: REDIS_PASSWORD
  displayName: redis_password
  description: redis password
  value: mypassword
  required: true

objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${REDIS_NAME}-secret
  type: Opaque
  stringData:
    redis-config: |
      maxmemory 20mb
      maxmemory-policy allkeys-lru
      appendonly yes
      appendfilename "appendonly.aof"
      no-appendfsync-on-rewrite no
      auto-aof-rewrite-percentage 100
      auto-aof-rewrite-min-size 64mb
      requirepass ${REDIS_PASSWORD}
    redis-password: ${REDIS_PASSWORD}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${REDIS_NAME}-data
  spec:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 100Mi
- apiVersion: v1
  kind: Service
  metadata:
    name: ${REDIS_NAME}-service
    labels:
      app: ${REDIS_NAME}
  spec:
    selector:
      app: ${REDIS_NAME}
    ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
    - name: redis-exporter
      protocol: TCP
      port: 9121
      targetPort: 9121
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    name: ${REDIS_NAME}
    labels:
      app: ${REDIS_NAME}
      release: prometheus
  spec:
    selector:
      matchLabels:
        app: ${REDIS_NAME}
    endpoints:
    - port: redis-exporter
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${REDIS_NAME}
    labels:
      app: ${REDIS_NAME}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ${REDIS_NAME}
    template:
      metadata:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9121"
        labels:
            app: ${REDIS_NAME}
      spec:
        containers:
        - name: ${REDIS_NAME}
          image: docker.io/redis:6
          imagePullPolicy: IfNotPresent
          command:
            - redis-server
            - "/redis-master/redis.conf"
          ports:
          - containerPort: 6379
          volumeMounts:
          - mountPath: /data
            name: data
          - mountPath: /redis-master
            name: config
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
        - name: redis-exporter
          image: oliver006/redis_exporter:latest
          env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: redis-password
          - name: REDIS_ADDR
            value: "localhost:6379"
          resources:
            requests:
              cpu: 300m
              memory: 300Mi
          ports:
          - containerPort: 9121
        volumes:
          - name: data
            persistentVolumeClaim:
              claimName: ${REDIS_NAME}-data
          - name: config
            secret:
              secretName: ${REDIS_NAME}-secret
              items:
              - key: redis-config
                path: redis.conf
