apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: redis-template-instance
  namespace: redis
spec:
  clustertemplate:
    metadata:
      name: redis-template
    parameters:
    - name: REDIS_NAME
      value: "tmax"
    - name: REDIS_PASSWORD
      value: "mypassword"