apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: nexus-package-server-instance
  namespace: default
  annotations:
    template-version: 5.0.2
    tested-operator-version: v0.2.0
spec:
  clustertemplate:
    metadata:
      name: nexus-package-server
    parameters:
    - name: DEPLOY_NAME
      value: nexus-private-1
    - name: STORAGE
      value: 10Gi

