apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: nexus-package-server-instance
  namespace: default
  annotations:
    template-version: 5.0.5
    tested-operator-version: 0.2.5
spec:
  clustertemplate:
    metadata:
      name: nexus-package-server
    parameters:
    - name: DEPLOY_NAME
      value: nexus-private-1
    - name: STORAGE
      value: 10Gi
    - name: STORAGE_CLASS
      value: csi-cephfs-sc

